<h1>Equipo 3</h1>
<table>
    <tr>
        <th>Dato</th>
        <th>Valor</th>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>{{nombre1}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{email1}}</td>
    </tr>
    <tr>
        <td>Titulo</td>
        <td>{{title1}}</td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>{{nombre2}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{email2}}</td>
    </tr>
    <tr>
        <td>Titulo</td>
        <td>{{title2}}</td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>{{nombre3}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{email3}}</td>
    </tr>
    <tr>
        <td>Titulo</td>
        <td>{{title3}}</td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>{{nombre4}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{email4}}</td>
    </tr>
    <tr>
        <td>Titulo</td>
        <td>{{title4}}</td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>{{nombre5}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{email5}}</td>
    </tr>
    <tr>
        <td>Titulo</td>
        <td>{{title5}}</td>
    </tr>
</table>