<h1>Mi Ficha de Desarrollador</h1>
<table>
    <tr>
        <th>Dato</th>
        <th>Valor</th>
    </tr>
    <tr>
        <td>Nombre</td>
        <td>{{nombre}}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>{{email}}</td>
    </tr>
    <tr>
        <td>Titulo</td>
        <td>{{title}}</td>
    </tr>
</table>